Complete the new design of on-boarding pages
Quarantine-Help/quarantine-help-hybrid pull request #79
Opened 2020-11-16 20:01 UTC by naveenpanickal

## Description

- Set the new design for the onboarding pages. [Page1](https://xd.adobe.com/view/7c6474dd-3491-4dc1-b5f9-4c91301be22e-2937/specs/)  [Page2](https://xd.adobe.com/view/7c6474dd-3491-4dc1-b5f9-4c91301be22e-2937/screen/1c345141-a781-4a31-8d8b-60508b494bbb/specs/)
- Add new logo.
- change the color theme to the latest design.

## Screenshots
### Prototype
![Page1](https://user-images.githubusercontent.com/52797241/99301095-738e7c80-2873-11eb-988c-7037942d1003.png)
![page2](https://user-images.githubusercontent.com/52797241/99301101-75584000-2873-11eb-8242-a698cab1ec05.png)

### App
![page1onb](https://user-images.githubusercontent.com/52797241/99301517-1b0baf00-2874-11eb-834b-355e51767140.png)
![onb2completed](https://user-images.githubusercontent.com/52797241/99301524-1cd57280-2874-11eb-8c76-f7f4efeb5759.png)

## Types of changes

- [X] Added new icon.
- [X] Changed the theme
- [X] Deleted the third page
- [X] Change the button theme

2020-11-18 10:36 UTC, sebinbenjamin requested changes

2020-11-18 10:36 UTC, sebinbenjamin commented on src/app/pages/about-us/about-us.page.ts
> +import { defaultUserType } from 'src/app/constants/core-api';
Please re-order the imports

2020-11-18 18:02 UTC, naveenpanickal commented
> Please do check if the page/slide progress indicator dot is missing.
> ![image](https://user-images.githubusercontent.com/4099066/99519733-1d4a4680-29f7-11eb-97e4-e36db722fc7b.png)

Yes

2020-11-19 04:30 UTC, sebinbenjamin approved these changes

2020-11-19 04:31 UTC, sebinbenjamin commented
> > Please do check if the page/slide progress indicator dot is missing.
> > ![image](https://user-images.githubusercontent.com/4099066/99519733-1d4a4680-29f7-11eb-97e4-e36db722fc7b.png)
> 
> Yes, it is there.

Can you update the screenshots?

2020-11-19 04:38 UTC, merged